// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJu78Q6ZEHuozGhgD4rglh5uh6TfhrDlg',
    appId: '1:791724744840:android:92b9a81c11e0f9f2bbbf3d',
    messagingSenderId: '791724744840',
    projectId: 'myflutterapplists',
    storageBucket: 'myflutterapplists.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj1x8nfwbWbw0AE3ei17IWHpeB4FaZCQM',
    appId: '1:791724744840:ios:1732f5d58ed0aaf6bbbf3d',
    messagingSenderId: '791724744840',
    projectId: 'myflutterapplists',
    storageBucket: 'myflutterapplists.appspot.com',
    iosBundleId: 'com.3nailstech.mylistapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj1x8nfwbWbw0AE3ei17IWHpeB4FaZCQM',
    appId: '1:791724744840:ios:e9ed9d1e62e40eb0bbbf3d',
    messagingSenderId: '791724744840',
    projectId: 'myflutterapplists',
    storageBucket: 'myflutterapplists.appspot.com',
    iosBundleId: 'com.3nailstech.mylistapp.RunnerTests',
  );
}
